version: '3'

services:

  # elasticsearch
  elastic01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    container_name: elastic01
    restart: 'no'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # sudo mkdir elastic01-data && sudo chown -R 1000:1000 elastic01-data
      - ./elastic01-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
      discovery.type: 'single-node'
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - elastic

  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.0
    container_name: kibana
    restart: 'no'
    environment:
      ELASTICSEARCH_HOSTS: http://elastic01:9200/
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elastic01
    networks:
      - elastic

volumes:
  elastic01:
    driver: local

networks:
  elastic:
    driver: bridge
