version '3'

services:

  # elasticsearch
  elastic01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    container_name: elastic01
    restart: 'no'
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
      cluster.name: elastic
      bootstrap.memory_lock: 'true'
      discovery.type: 'single-node'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic01-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.01:9200:9200
    expose:
      - 9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.0
    container_name: kibana
    restart: 'no'
    environment:
        ELASTICSEARCH_HOSTS: http://127.0.0.1:9200
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elastic01
    networks:
      - elastic

volumes:
  elastic01:
    driver: local


networks:
  elastic:
    driver: bridge

